Div/original button
2019-miraikeitai-org/ap_2_iOS_Summar pull request #8
Opened 2019-08-20 06:34 UTC by yushi-hosokawa

close #2 
大変時間がかかってごめんなさい
引数の数だけボタンを作るというのが結局できず、４つのボタンを作る限定のプログラムになってしまいました。

2019-08-22 15:35 UTC, reud requested changes
あざす！　ロジックとかは問題ない気がするので！命名規則だけお願いします！
コメントがわかりやすくて助かります！

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/MakeButton.swift
> +
[Swiftガイドライン的な - Qiita](https://qiita.com/masanori-inukai/items/663e23f2390bf52fcffd#%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87)

折角なので命名規則に合わせて欲しいな！

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +            newbutton.animation(animation : subbutton1.SubButtonUI, Countbutton: countbuttonn,buttonNumber: subbutton1.buttonnumber , Counter :counter)
ここインデントずれてるのほんの少し気になるのでコード整形してくれると見やすくて助かります
[Xcodeでコード整形 - Qiita](https://qiita.com/redpanda/items/232ff66e6a782ccbfb2e)

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +        newbutton.animation(animation : subbutton2.SubButtonUI, Countbutton: countbuttonn,buttonNumber: subbutton2.buttonnumber, Counter: counter)
typoあった！　`Countbutton: countbuttonn`

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +    var counter :Float  = -1.0
counter, bool (boolean) 辺りの方が綺麗かなと思う！
 counter = !counter とかに出来ると思うので

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +    func appearbutton (target :UIButton , number:Int){
これは多分MakeButton.swiftに入れられないかな！　#selector(self.pushButton)辺りかself.view.addSubview(target)がViewControllerに依存してそうな気がする

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +    func appearbutton (target :UIButton , number:Int){
そのままでおk！　動作もわかりやすいので！

2019-08-22 15:35 UTC, reud commented on iOS-Practice-Team-Working/sceneB/MakeButton.swift
> +
🔺書いてもらったファイル全体についてです！

2019-08-23 07:28 UTC, yushi-hosokawa commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +    func appearbutton (target :UIButton , number:Int){
了解ー

2019-08-23 07:28 UTC, yushi-hosokawa commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +    var counter :Float  = -1.0
・最初にviewcontrollerのcounterを定義するところで
var counter :Bool = true

・animation関数の中で
var sign :Float =1.0
if counter {sign = -1.0 }
このsignを使って計算

・viewcontrollerの奇数か偶数で数えるところで
counter = !counter

こんな感じに直したんだけどいいかな？

2019-08-23 07:28 UTC, yushi-hosokawa commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +        newbutton.animation(animation : subbutton2.SubButtonUI, Countbutton: countbuttonn,buttonNumber: subbutton2.buttonnumber, Counter: counter)
azasu!

2019-08-23 07:28 UTC, yushi-hosokawa commented on iOS-Practice-Team-Working/sceneB/BViewController.swift
> +            newbutton.animation(animation : subbutton1.SubButtonUI, Countbutton: countbuttonn,buttonNumber: subbutton1.buttonnumber , Counter :counter)
なおした！

2019-08-23 07:28 UTC, yushi-hosokawa commented on iOS-Practice-Team-Working/sceneB/MakeButton.swift
> +
全然気にしないで適当に書いてたから気をつけます！
直しました

2019-09-01 01:03 UTC, reud approved these changes

2019-09-01 01:03 UTC, reud commented on iOS-Practice-Team-Working/sceneB/MakeButton.swift
> +
あざす！　命名規則が統一されていると、コードの検索とかに役立つので習慣があると良いよ！

2019-09-23 07:43 UTC, rei-yoshi approved these changes

2019-09-23 07:44 UTC, merged